### ISSUE TITLE
How can I get the debug version of openjdk8 on linux? 

### ISSUE THREAD

**Issue by dreamdevil00** [ojdkbuild/contrib_jdk8u-ci#2]
Could you please provide debug build travis config and releases ?

**Comment by ojdkbuild** [comment]
Sorry, missed this question. To to a debug build, you need to use `--with-debug-level=slowdebug` or `--with-debug-level=fastdebug` configure flag. If you change this flag in existing config in this repo - it should work fine.

I would like to not include debug builds on Travis, because for vanilla Linux builds rebuild is usually quite easy, and when debugging something you likely need to repeatedly rebuild anyway.

**Comment by dreamdevil00** [comment]
Thanks for your explaination.
